version: "3.9"
services:
  client:
    build: .
    volumes:
      - "m2:/root/.m2"
    deploy:
      replicas: 4
    environment:
      - SERVER_HOST=server
networks:
  default:
    external:
      name: peer
volumes:
  m2: